{
 "title": "Conduit",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Non Load Shedding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(conduit_http_server_processing_delay_seconds_sum{application=\"nls-server\"}[1m]) / rate(conduit_http_server_processing_delay_seconds_count{application=\"nls-server\"}[1m])",
     "legendFormat": "Delay"
    },
    {
     "expr": "rate(conduit_http_server_processing_time_seconds_sum{application=\"nls-server\"}[1m]) / rate(conduit_http_server_processing_time_seconds_count{application=\"nls-server\"}[1m])",
     "legendFormat": "Processing time"
    }
   ]
  },
  {
   "title": "Response Status Counts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\", application=\"nls-server\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Server JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum by(application) (jvm_threads_states_threads{application=\"nls-server\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Client-observed duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(application) (rate(http_client_requests_seconds_sum{application=\"nls-client\", uri!=\"/actuator/prometheus\"}[1m])) / sum by(application) (rate(http_client_requests_seconds_count{application=\"nls-client\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Client-observed in-flight requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Client Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_client_requests_concurrency{application=\"nls-client\"}",
     "legendFormat": "Concurrency"
    }
   ]
  },
  { "title": "Load Shedding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(conduit_http_server_processing_delay_seconds_sum{application=\"ls-server\"}[1m]) / rate(conduit_http_server_processing_delay_seconds_count{application=\"ls-server\"}[1m])",
     "legendFormat": "Delay"
    },
    {
     "expr": "rate(conduit_http_server_processing_time_seconds_sum{application=\"ls-server\"}[1m]) / rate(conduit_http_server_processing_time_seconds_count{application=\"ls-server\"}[1m])",
     "legendFormat": "Processing time"
    }
   ]
  },
  {
   "title": "Response Status Counts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\", application=\"ls-server\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Server JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "sum by(application) (jvm_threads_states_threads{application=\"ls-server\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Client-observed duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(application) (rate(http_client_requests_seconds_sum{application=\"ls-client\", uri!=\"/actuator/prometheus\"}[1m])) / sum by(application) (rate(http_client_requests_seconds_count{application=\"ls-client\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Client-observed in-flight requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Client Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_client_requests_concurrency{application=\"ls-client\"}",
     "legendFormat": "Concurrency"
    }
   ]
  }
 ]
}