{
 "title": "Flow Metrics - Conduit - Side by Side (for slides)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server 1 (NLS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Received - NLS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(http_client_requests_initiated_total{application=\"nls-client\"}[1m])",
     "legendFormat": "Number of Requests"
    }
   ]
  },
  {
   "title": "Requests Received - LS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "increase(http_client_requests_initiated_total{application=\"ls-client\"}[1m])",
     "legendFormat": "Number of Requests"
    }
   ]
  },
  {
   "title": "Client Latency - NLS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(application) (rate(http_client_requests_seconds_sum{application=\"nls-client\", uri!=\"/actuator/prometheus\"}[1m])) / sum by(application) (rate(http_client_requests_seconds_count{application=\"nls-client\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Client Latency - LS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(application) (rate(http_client_requests_seconds_sum{application=\"ls-client\", uri!=\"/actuator/prometheus\"}[1m])) / sum by(application) (rate(http_client_requests_seconds_count{application=\"ls-client\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Processing Time - NLS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(conduit_http_server_processing_time_seconds_sum{application=\"nls-server\"}[1m]) / rate(conduit_http_server_processing_time_seconds_count{application=\"nls-server\"}[1m])",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "Processing Time - LS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(conduit_http_server_processing_time_seconds_sum{application=\"ls-server\"}[1m]) / rate(conduit_http_server_processing_time_seconds_count{application=\"ls-server\"}[1m])",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "Response Statuses - NLS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_client_requests_completed_total{application=\"nls-client\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response Statuses - LS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 31 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_client_requests_completed_total{application=\"ls-client\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "In flight Requests (WIP) - NLS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 41 },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "In flight Requests (WIP) - LS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 41 },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "Age - NLS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(conduit_http_server_processing_delay_seconds_sum{application=\"nls-server\"}[1m]) / rate(conduit_http_server_processing_delay_seconds_count{application=\"nls-server\"}[1m])",
     "legendFormat": "Waiting Time"
    },
    {
     "expr": "rate(conduit_http_server_processing_time_seconds_sum{application=\"nls-server\"}[1m]) / rate(conduit_http_server_processing_time_seconds_count{application=\"nls-server\"}[1m])",
     "legendFormat": "Processing time"
    }
   ]
  },
  {
   "title": "Age - LS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(conduit_http_server_processing_delay_seconds_sum{application=\"ls-server\"}[1m]) / rate(conduit_http_server_processing_delay_seconds_count{application=\"ls-server\"}[1m])",
     "legendFormat": "Waiting time"
    },
    {
     "expr": "rate(conduit_http_server_processing_time_seconds_sum{application=\"ls-server\"}[1m]) / rate(conduit_http_server_processing_time_seconds_count{application=\"ls-server\"}[1m])",
     "legendFormat": "Processing time"
    }
   ]
  },
  { "title": "Server 2 (LS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } }
 ]
}